config/routes.rb
Rails.application.routes.draw do
  

  get 'admin' => 'admin#index' 
  controller :sessions do
    get 'login' => :new
    post 'login' => :create 
    delete 'logout' => :destroy
  end
  # Other routes
  get 'sessions/create'
  get 'sessions/destroy'
  get 'sessions/new'
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products do
    get :who_bought, on: :member
  end

  # Root route
  root 'store#index', as: 'store_index'

  # Health check route
  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
    <%= render cart %>
  </div>
<% else %>
  <div id="cart"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PragProg Books Online Store</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <header class="bg-green-700">
    <%= image_tag 'book1.png', alt: 'The Pragmatic Bookshelf', size: '100x100' %>
    <h1><%= @page_title %></h1>
  </header>

  <section class="flex">
    <%= render partial: 'layouts/cart', locals: {cart: @cart } %>
    <nav class="bg-green-900 p-6">
      <%= render partial: 'layouts/cart', locals: {cart: @cart } %>
      <ul class="text-gray-300 leading-8">
        <li><a href="/">Home</a></li>
        <li><a href="/questions">Questions</a></li>
        <li><a href="/news">News</a></li>
        <li><a href="/contact">Contact</a></li>
      </ul>

      <% if session[:user_id] %>
      <hr class="my-2">
      <ul class="text-gray-300 leading-8">
      <li><%= link_to 'Orders', orders_path %></li>
      <li><%= link_to 'Products', products_path %></li>
      <li><%= link_to 'Users', users_path %></li>
      <li><%= button_to 'Logout', logout_path, method: :delete %></li>
      </ul>
      <% end %>
    </nav>

    <main class="container mx-auto mt-4 px-5 flex">
      <%= yield %>
    </main>
  </section>
</body>
</html>